### ISSUE TITLE
Auto-centroid put-on-slit targets

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#117]
A suggestion from Roger is that put-on-slit automatically might automatically determine the centroid of the target rather than rely on user's ability to determine and click on the centroid.

Additionally (and perhaps a separate issue) he suggests a "nudge" button to fine-tune target position on the slit, or to use for targets that can't easily be centroided (faint targets, or in a crowded field).

**Comment by chazshapiro** [comment]
This is non-trivial if only because people will want to turn it off and on (e.g. what if you want to observe the edge of a galaxy).  So that requires more buttons and DS9 hackery (DS9 has no parameter memory).

Plus, this is aiming for a level of accuracy we may not even have in open loop mode.  Closing this issue for housekeeping, and we can think about it later if it's a popular request.

The nudge button is covered by the 4-way jog buttons.
