### ISSUE TITLE
Complete/Verify FITS headers in ACAM and slit cam images

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#39]
Make sure all needed FITS headers are present and correct, whether from the camera or the simulator.

CF said the WCS parameters were wrong in the first calibration images, but that may have just been the old (incorrect) FPoffsets parameters.

- WCS parameters -- from FPoffsets (1st image) or kept from astrometry solver
- RA, Dec, cass angle, airmass from TCS -- won't/shouldn't match the WCS parameters
- ACAM exptime
- ACAM filter
- Gain (consistent keyword regardless of whether using EM)
- Saturation level (pixel value that is considered saturated)
- MJD / time of obs
- Focus value
- We may also want PIXSCALE and POSANG headers.

Others?

**Comment by jenniferwillow** [comment]
Question?  Do we need the RA,Dec and cass angle from the telescope in the header?  The CRVAL1,2 would not match the RA and Dec.  Do we have a filter mechanism to control?  We have a filter wheel on DBSP slit viewer.  Do we intend to use this filter wheel?
Jennifer

On Jun 8, 2023, at 10:45 AM, Chaz Shapiro ***@***.******@***.***>> wrote:



Assigned #39<https://github.com/CaltechOpticalObservatories/NGPS/issues/39> to @jenniferwillow<https://github.com/jenniferwillow>.

**Comment by chazshapiro** [comment]
Yes we need the telescope coordinates for calibration.

**Comment by chazshapiro** [comment]
Sorry this is an issue for ACAM and the slit camera -- all headers should be present in images for both

**Comment by astronomerdave** [comment]
@jenniferwillow yes, there is a filter wheel

**Comment by chazshapiro** [comment]
Do we have progress on this?  I think we want it closed by Monday, no?

**Comment by chazshapiro** [comment]
Here's what I found from 20230622 (ngc_focus_5.fits and a random slitcam image) :

**acam only**:
CRVALs, RA/DEC, TELRA/TELDEC are off by ~1.7 deg
PC is incorrect -- flipped and rotated; looks like image itself needs to be flipped
ACAM filter -- missing

**acam and slitcam**:
EQINOX -- misspelled and wrong
Various headers look like just defaults (HA, DATE, etc.)
OPTICAL -- if using, should match focus; unneeded anyway since we were able to focus without PPL tools
PIXSCALE -- change to arcsec/pixel
POSANG -- missing, use FPoffsets output

**Comment by jenniferwillow** [comment]
This list requires some context.  You’re making a lot of claims without context and I have no idea what you’re talking about.
Jennifer

Sent from my iPad

On Jun 23, 2023, at 5:41 PM, Chaz Shapiro ***@***.***> wrote:

﻿

Here's what I found from 20230622 (ngc_focus_5.fits and a random slitcam image) :

acam only:
CRVALs, RA/DEC, TELRA/TELDEC are off by ~1.7 deg
PC is incorrect -- flipped and rotated; looks like image itself needs to be flipped
ACAM filter -- missing

acam and slitcam:
EQINOX -- misspelled and wrong
Various headers look like just defaults (HA, DATE, etc.)
OPTICAL -- if using, should match focus; unneeded anyway since we were able to focus without PPL tools
PIXSCALE -- change to arcsec/pixel
POSANG -- missing, use FPoffsets output

**Comment by chazshapiro** [comment]
@jenniferwillow I'm not sure what you mean - I'm just adding to the thread

https://github.com/CaltechOpticalObservatories/NGPS/issues/39

**Comment by cfremling** [comment]
OK, it would be critical to fix CRVALS, PC/CD matrix on acam so that we can test acquisition and guiding properly
Do you agree we should make a flip on acam in y-axis hardcoded into the camera software, Chaz? I guess that was what we did on our first night but somehow it didnt stick permanently.
What do you need Jennifer to correct the initial guess on the CRVAL and PC matrix?

the rest of these should be simple to address


Christoffer
________________________________

**Comment by chazshapiro** [comment]
Yes looks like we need to do the acam flip again.  I think we all need to look at the WCS parameters together because I don't get how these can be so far off.  Since the acam center is only ~0.13 deg away from the scope center, all RA/DEC coordinates (acam or TCS) should be well within 1 deg of the astrometry.net solution but they're not.

**Comment by chazshapiro** [comment]
Astrometry.net thinks [our calibration cluster](https://nova.astrometry.net/user_images/8091144#grid) is at:
(deg 205.547 28.377)  = (13:42:11.28    28:22:37.20)

But our headers say:
RA      = '13:35:24.587'       / Right Ascension                                
DEC     = '+28:22:37.808'      / Declination                                    
TELRA   = '13:42:40.660'       / Telecscope Right Ascension                     
TELDEC  = '+28:27:29.200'      / Telescope Declination
CRVAL1  =   203.85244500000002 / X reference coordinate value (deg)             
CRVAL2  =            28.377169 / Y reference coordinate value (deg) 

So all of the RA headers are significantly off

**Comment by chazshapiro** [comment]
I've added Gain to the list of needed headers
