### ISSUE TITLE
Zoom items in GUI View menu only change font size

### ISSUE THREAD

**Issue by chazshapiro** [CaltechOpticalObservatories/NGPS#62]
<img width="271" alt="Screenshot 2024-07-12 at 8 53 32 AM" src="https://github.com/user-attachments/assets/96cd20ef-942d-48a6-aad2-6c952f61237d">

Except for OTM Output, the menu items do little to nothing.  What do we want them to do?

The zoom items only change the font size of the main table and not e.g. the cell spacing.  It's awkward.

**Comment by astronomerdave** [comment]
I don't know where "Basic" and "Detailed" came from, as they are not in the design document. Here is what is in the design document for the View menu:

- OTM Output.  Opens a floating popup window to display the raw OTM output. This popup features a text window and a "Close" button which closes the popup window. 
- Zoom in. Increase font size for target list and details only. I.e. fonts on menus and buttons are unaffected.  Greyed-out when zoom at max-allowed.
- Zoom out. Decrease font size for target list. Greyed-out when zoom at max-allowed. 
- Plot... Opens a dialog window for plot controls, including what to plot, formatting options, etc. and includes a plot button (no ellipses) within that dialog window to display the plot. Plots will appear always in the same window, i.e. plots are displayed in their own floating window but repeated clicks will continue to display each new plot in the same plot display window. 

The Zoom should only be included if it works, but if it can't be made so that it's not "awkward" then better to eliminate it.

Please update design document as this pulldown menu evolves.

**Comment by chazshapiro** [comment]
I removed all but the Zoom items.  It would be very nice if they increased the row size and not just the font.  Also the column headers don't update until you mouseover them.

I will leave them as placeholders for now.  If we can't get that working, we'll delete them.

Here is the result of zooming in:

![Screenshot 2024-07-12 at 2 26 51 PM](https://github.com/user-attachments/assets/125a7392-2520-4c12-a837-2df9e3834671)

**Comment by chazshapiro** [comment]
OTM Output was moved to the Tools menu.  I have no idea what Plot is even referring to.

**Comment by chazshapiro** [comment]
Rows now increase size with font

**Comment by astronomerdave** [comment]
Zoom in/out with the keyboard (ctrl + -) does not affect the column titles; only the zoom controls on the menu will change also the column headers.

**Comment by chazshapiro** [comment]
The row headers catch up in size if you wave a mouse over them.  I'll look at it

**Comment by chazshapiro** [comment]
fixed
